### ISSUE TITLE
ZFS Layout

### ISSUE THREAD

**Issue by WaaromZoMoeilijk** [ich777/unraid-kernel-helper-plugin#1]
Hello, 

Great plugin!

I see the details of zpool status are a bit messed, is that only on my installation?
![DeepinScreenshot_select-area_20201207002827](https://user-images.githubusercontent.com/13510720/101296342-2888d900-3823-11eb-90c5-3ba26b3e3353.png)

I have used a script for a long time, even when i was on FreeNAS. It shows zpool status output the same as zfs list on the plugin page. Just need help converting it to html.

![DeepinScreenshot_select-area_20201207003231](https://user-images.githubusercontent.com/13510720/101296419-b5339700-3823-11eb-935d-a3cb4600b933.png)

Also i can't get var $scrubTS to work. 

Might be of use, might not. Willing to help upgrade the ZFS frontend!

```
#!/bin/sh
 
host=$(hostname -s | tr '[:lower:]' '[:upper:]')
logfile="/tmp/zpool_report.tmp"
subject="ZPool Status Report for ${host}"
pools=$(zpool list -H -o name)
usedWarn=75
usedCrit=90
scrubAgeWarn=30
warnSymbol="?"
critSymbol="!"

###### summary ######
(
  echo "########## ZPool status report summary for all pools on server ${host} ##########"
  echo ""
  echo "+--------------+--------+------+------+------+----+----+--------+------+-----+"
  echo "|Pool Name     |Status  |Read  |Write |Cksum |Used|Frag|Scrub   |Scrub |Last |"
  echo "|              |        |Errors|Errors|Errors|    |    |Repaired|Errors|Scrub|"
  echo "|              |        |      |      |      |    |    |Bytes   |      |Age  |"
  echo "+--------------+--------+------+------+------+----+----+--------+------+-----+"
) > ${logfile}

for pool in $pools; do
  frag="$(zpool list -H -o frag "$pool")"
  status="$(zpool list -H -o health "$pool")"
  errors="$(zpool status "$pool" | grep -E "(ONLINE|DEGRADED|FAULTED|UNAVAIL|REMOVED)[ \t]+[0-9]+")"
  readErrors=0
  for err in $(echo "$errors" | awk '{print $3}'); do
    if echo "$err" | grep -E -q "[^0-9]+"; then
      readErrors=1000
      break
    fi
    readErrors=$((readErrors + err))
  done
  writeErrors=0
  for err in $(echo "$errors" | awk '{print $4}'); do
    if echo "$err" | grep -E -q "[^0-9]+"; then
      writeErrors=1000
      break
    fi
    writeErrors=$((writeErrors + err))
  done
  cksumErrors=0
  for err in $(echo "$errors" | awk '{print $5}'); do
    if echo "$err" | grep -E -q "[^0-9]+"; then
      cksumErrors=1000
      break
    fi
    cksumErrors=$((cksumErrors + err))
  done
  if [ "$readErrors" -gt 999 ]; then readErrors=">1K"; fi
  if [ "$writeErrors" -gt 999 ]; then writeErrors=">1K"; fi
  if [ "$cksumErrors" -gt 999 ]; then cksumErrors=">1K"; fi
  used="$(zpool list -H -p -o capacity "$pool")"

  scrubRepBytes="N/A"
  scrubErrors="N/A"
  scrubAge="N/A"
  if [ "$(zpool status "$pool" | grep "scan" | awk '{print $2}')" = "scrub" ]; then
    scrubRepBytes="$(zpool status "$pool" | grep "scan" | awk '{print $4}')"
    #if [ "$fbsd_relver" -gt 1101000 ]; then
    scrubErrors="$(zpool status "$pool" | grep "scan" | awk '{print $10}')"
    scrubDate="$(zpool status "$pool" | grep "scan" | awk '{print $17"-"$14"-"$15"_"$16}')"
    #else
    #  scrubErrors="$(zpool status "$pool" | grep "scan" | awk '{print $8}')"
    #  scrubDate="$(zpool status "$pool" | grep "scan" | awk '{print $15"-"$12"-"$13"_"$14}')"
    #fi
    scrubTS="$(date "+%Y-%b-%-e_%H:%M:%S" "$scrubDate" "+%s")"
    currentTS="$(date "+%s")"
    scrubAge=$((((currentTS - scrubTS) + 43200) / 86400))
  fi
  if [ "$status" = "FAULTED" ] \
  || [ "$used" -gt "$usedCrit" ] \
  || ( [ "$scrubErrors" != "N/A" ] && [ "$scrubErrors" != "0" ] )
  then
    symbol="$critSymbol"
  elif [ "$status" != "ONLINE" ] \
  || [ "$readErrors" != "0" ] \
  || [ "$writeErrors" != "0" ] \
  || [ "$cksumErrors" != "0" ] \
  || [ "$used" -gt "$usedWarn" ] \
  || [ "$scrubRepBytes" != "0" ] \
  || [ "$(echo "$scrubAge" | awk '{print int($1)}')" -gt "$scrubAgeWarn" ]
  then
    symbol="$warnSymbol"
  else
    symbol=" "
  fi
  (
  printf "|%-12s %1s|%-8s|%6s|%6s|%6s|%3s%%|%4s|%8s|%6s|%5s|\n" \
  "$pool" "$symbol" "$status" "$readErrors" "$writeErrors" "$cksumErrors" \
  "$used" "$frag" "$scrubRepBytes" "$scrubErrors" "$scrubAge"
  ) >> ${logfile}
  done

(
  echo "+--------------+--------+------+------+------+----+----+--------+------+-----+"
) >> ${logfile}

###### for each pool ######
for pool in $pools; do
  (
  echo ""
  echo "########## ZPool status report for ${pool} ##########"
  echo ""
  zpool status -v "$pool"
  ) >> ${logfile}
done
```

**Comment by ich777** [comment]
Thank you for reporting that.
Don't know if it makes much sense to upgrade the plugin itself since when Unraid 6.9.0 launches you can install everything through the CA App as a plugin Nvidia/DVB/ZFS/MFT Tools (btw. it's already possible to do that on beta35+ but you have to be at least on beta35+ to see the plugins in the CA App).

This plugin will then become depricated I think but I'm not 100% sure.

**Comment by WaaromZoMoeilijk** [comment]
Hmm well alright then, thanks for the info. I could not get beta 35 to work on my current setup so ill wait for 6.9. Anyway I'd like to keep using a portion of it or just the ZFS/iscsi display option.Are you using ZFS yourself on unraid?If so we could collaborate on a ZFS frontend (if not done by limetech devs yet)Kind regards,EzraOp 7 dec. 2020 12:25 schreef Christoph <notifications@github.com>:
Thank you for reporting that.
Don't know if it makes much sense to upgrade the plugin itself since when Unraid 6.9.0 launches you can install everything through the CA App as a plugin Nvidia/DVB/ZFS/MFT Tools (btw. it's already possible to do that on beta35+ but you have to be at least on beta35+ to see the plugins in the CA App).
This plugin will then become depricated I think but I'm not 100% sure.

**Comment by ich777** [comment]
What is not working on beta35? Did you also create a image with the unraid kernel helper (if so don't do this).
All plugins for Nvidia, iSCSI,... are available in the CA App.
Just upgrade to stock beta35 and then go to the CA App

EDIT: I don't use ZFS on Unraid, not my usecase and not the way Unraid is designed. I created this feature on request.
I only use Nvidia, DVB, iSCSI and MFT

**Comment by ich777** [comment]
I close the issue for now...
